services:
  php:
    build:
      dockerfile: docker/php/Dockerfile
      context: .
      target: app
    volumes:
      - ./:/app
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    extra_hosts:
      - "host.docker.internal:host-gateway"
  nginx:
    image: nginx:alpine
    volumes:
      - ./docker/nginx/app.conf.template:/etc/nginx/templates/app.conf.template
    environment:
      PHP_FASTCGI_ADDR: php
      PHP_FASTCGI_PORT: 9000
    ports:
      - "20100:8080"
